# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "generic-ecs-deployment-bucket"
    dynamodb_table = "terraform-state-lock"
    encrypt        = true
    key            = "./terraform.tfstate"
    region         = "ap-southeast-1"
  }
}
